from django.db import models
from django.conf import settings

class Brief(models.Model):
    file = models.FileField(upload_to='uploaded_briefs/')
    description = models.TextField(blank=True, null=True)  # Generated by AI
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Brief {self.id} by {self.created_by}"
