# Generated by Django 5.2.4 on 2025-07-16 05:28

import brief.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brief', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brief',
            name='file',
            field=models.FileField(upload_to='uploads/briefs/', validators=[brief.models.validate_file_type]),
        ),
    ]
